
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 14;
  public static final int FUNCTION = 28;
  public static final int GREATER_THAN_EQUAL = 25;
  public static final int UMINUS = 5;
  public static final int LESS_THAN_EQUAL = 24;
  public static final int NOT_EQUAL = 21;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int BIGLPAREN = 11;
  public static final int INT = 42;
  public static final int ENDDO = 36;
  public static final int FOR = 37;
  public static final int MINUS = 4;
  public static final int WRITE = 47;
  public static final int GREATER_THAN = 23;
  public static final int RPAREN = 8;
  public static final int DRAW = 46;
  public static final int BIGRPAREN = 12;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int ENDFUNCTION = 29;
  public static final int CLPAREN = 9;
  public static final int OR = 18;
  public static final int COMMA = 51;
  public static final int RLPAREN = 10;
  public static final int ENDFOR = 39;
  public static final int ENDPROGRAM = 27;
  public static final int PLUS = 3;
  public static final int ASSIGN = 13;
  public static final int IF = 30;
  public static final int ID = 53;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int EQUAL = 20;
  public static final int error = 1;
  public static final int PROGRAM = 26;
  public static final int LINE = 50;
  public static final int NUMBER = 52;
  public static final int MOD = 16;
  public static final int COLOR = 49;
  public static final int REAL = 43;
  public static final int MOVE = 45;
  public static final int TIMES = 6;
  public static final int ENDIF = 33;
  public static final int ELSE = 32;
  public static final int TO = 38;
  public static final int WHILE = 34;
  public static final int CLEAR = 44;
  public static final int THEN = 31;
  public static final int STRING = 41;
  public static final int LESS_THAN = 22;
  public static final int DO = 35;
  public static final int EXPONENT = 15;
  public static final int SET = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "CLPAREN",
  "RLPAREN",
  "BIGLPAREN",
  "BIGRPAREN",
  "ASSIGN",
  "DIVIDE",
  "EXPONENT",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "EQUAL",
  "NOT_EQUAL",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_THAN_EQUAL",
  "GREATER_THAN_EQUAL",
  "PROGRAM",
  "ENDPROGRAM",
  "FUNCTION",
  "ENDFUNCTION",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDDO",
  "FOR",
  "TO",
  "ENDFOR",
  "RETURN",
  "STRING",
  "INT",
  "REAL",
  "CLEAR",
  "MOVE",
  "DRAW",
  "WRITE",
  "SET",
  "COLOR",
  "LINE",
  "COMMA",
  "NUMBER",
  "ID"
  };
}

